#ifndef _F9_CONF_H_
#define _F9_CONF_H_

// Platform
#define CONFIG_BOARD_STM32F4DISCOVERY 1
//#define  CONFIG_BOARD_STM32F429DISCOVERY 1
//#define  CONFIG_BOARD_STM32P103 1
//#define  CONFIG_BITMAP_BITBAND 1
//#define  CONFIG_FPU 1
//#define  CONFIG_STDIO_NODEV 1
#define CONFIG_STDIO_USE_DBGPORT 1
//#define CONFIG_DBGPORT_USE_USART1 1
//#define CONFIG_DBGPORT_USE_USART2 1
#define CONFIG_DBGPORT_USE_USART4 1

// Limitations
#define CONFIG_MAX_THREADS 32
#define CONFIG_MAX_KT_EVENTS 64
#define CONFIG_MAX_ASYNC_EVENTS 32
#define CONFIG_MAX_ADRESS_SPACES 16
#define CONFIG_MAX_FPAGES 256

// Kernel Timer
#define CONFIG_KTIMER_TICKLESS 1
//#defineCONFIG_KTIMER_TICKLESS_VERIFY 1
#define CONFIG_KTIMER_TICKLESS_COMPENSATION 0
#define CONFIG_KTIMER_TICKLESS_INT_COMPENSATION 0
#define CONFIG_KTIMER_HEARTBEAT 65536
#define CONFIG_KTIMER_MINTICKS 128

// Flexible page tweaks
#define CONFIG_LARGEST_FPAGE_SHIFT 16
#define CONFIG_SMALLEST_FPAGE_SHIFT 8

// Thread tweaks
#define CONFIG_INTR_THREAD_MAX 256

// KIP tweaks
#define CONFIG_KIP_EXTRA_SIZE 128

// Kernel hacking
#define CONFIG_DEBUG 1
#define CONFIG_DEBUG_DEV_UART 1
//#define CONFIG_KDB 1
//#define CONFIG_KPROBES 1
//#define CONFIG_SYMMAP 1
//#define CONFIG_PANIC_DUMP_STACK 1
//#define CONFIG_LOADER 1

//#define INC_PLAT(x) <platform/stm32f429/x>
#define __CONCAT__(a,b) a ## b
#define _INC_PLAT(x) platform/stm32f4/x
#define INC_PLAT(x) <_INC_PLAT(x)>
#define BUILD_TIME __TIME__
#define MACH_TYPE "MACH_TYPE_MEH"
#define GIT_HEAD "GIT_HEAD_MEH"
#define STM32F4X
#include <stm32f4xx.h>
#define IRQn_NUM 128


#define CORE_CLOCK		(0x0a037a00) /* 168MHz */
#define SYSTICK_MAXRELOAD	(0x00ffffff)


// User IRQ
//#define CONFIG_WWDG_USER_IRQ 1
//#define CONFIG_PVD_USER_IRQ 1
//#define CONFIG_TAMP_STAMP_USER_IRQ 1
//#define CONFIG_RTC_WKUP_USER_IRQ 1
//#define CONFIG_FLASH_USER_IRQ 1
//#define CONFIG_RCC_USER_IRQ 1
//#define CONFIG_EXTI0_USER_IRQ 1
//#define CONFIG_EXTI1_USER_IRQ 1
//#define CONFIG_EXTI2_USER_IRQ 1
//#define CONFIG_EXTI3_USER_IRQ 1
//#define CONFIG_EXTI4_USER_IRQ 1
//#define CONFIG_DMA1_Stream0_USER_IRQ 1
//#define CONFIG_DMA1_Stream1_USER_IRQ 1
//#define CONFIG_DMA1_Stream2_USER_IRQ 1
//#define CONFIG_DMA1_Stream3_USER_IRQ 1
//#define CONFIG_DMA1_Stream4_USER_IRQ 1
//#define CONFIG_DMA1_Stream5_USER_IRQ 1
//#define CONFIG_DMA1_Stream6_USER_IRQ 1
//#define CONFIG_ADC_USER_IRQ 1
//#define CONFIG_CAN1_TX_USER_IRQ 1
//#define CONFIG_CAN1_RX_USER_IRQ 1
//#define CONFIG_CAN1_RX1_USER_IRQ 1
//#define CONFIG_CAN1_SCE_USER_IRQ 1
//#define CONFIG_EXTI9_5_USER_IRQ 1
//#define CONFIG_TIM1_BRK_TIM9_USER_IRQ 1
//#define CONFIG_TIM1_UP_TIM10_USER_IRQ 1
//#define CONFIG_TIM1_TRG_COM_TIM11_USER_IRQ 1
//#define CONFIG_TIM1_CC_USER_IRQ 1
//#define CONFIG_TIM2_USER_IRQ 1
//#define CONFIG_TIM3_USER_IRQ 1
//#define CONFIG_TIM4_USER_IRQ 1
//#define CONFIG_I2C1_EV_USER_IRQ 1
//#define CONFIG_I2C1_ER_USER_IRQ 1
//#define CONFIG_I2C2_EV_USER_IRQ 1
//#define CONFIG_I2C2_ER_USER_IRQ 1
//#define CONFIG_SPI1_USER_IRQ 1
//#define CONFIG_SPI2_USER_IRQ 1
//#define CONFIG_USART1_USER_IRQ 1
//#define CONFIG_USART2_USER_IRQ 1
//#define CONFIG_USART3_USER_IRQ 1
//#define CONFIG_EXTI15_10_USER_IRQ 1
//#define CONFIG_RTC_Alarm_USER_IRQ 1
//#define CONFIG_OTG_FS_WKUP_USER_IRQ 1
//#define CONFIG_TIM8_BRK_TIM12_USER_IRQ 1
//#define CONFIG_TIM8_UP_TIM13_USER_IRQ 1
//#define CONFIG_TIM8_TRG_COM_TIM14_USER_IRQ 1
//#define CONFIG_TIM8_CC_USER_IRQ 1
//#define CONFIG_DMA1_Stream7_USER_IRQ 1
//#define CONFIG_FSMC_USER_IRQ 1
//#define CONFIG_SDIO_USER_IRQ 1
//#define CONFIG_TIM5_USER_IRQ 1
//#define CONFIG_SPI3_USER_IRQ 1
//#define CONFIG_UART4_USER_IRQ 1
//#define CONFIG_UART5_USER_IRQ 1
//#define CONFIG_TIM6_DAC_USER_IRQ 1
//#define CONFIG_TIM7_USER_IRQ 1
//#define CONFIG_DMA2_Stream0_USER_IRQ 1
//#define CONFIG_DMA2_Stream1_USER_IRQ 1
//#define CONFIG_DMA2_Stream2_USER_IRQ 1
//#define CONFIG_DMA2_Stream3_USER_IRQ 1
//#define CONFIG_DMA2_Stream4_USER_IRQ 1
//#define CONFIG_ETH_USER_IRQ 1
//#define CONFIG_ETH_WKUP_USER_IRQ 1
//#define CONFIG_CAN2_TX_USER_IRQ 1
//#define CONFIG_CAN2_RX0_USER_IRQ 1
//#define CONFIG_CAN2_RX1_USER_IRQ 1
//#define CONFIG_CAN2_SCE_USER_IRQ 1
//#define CONFIG_OTG_FS_USER_IRQ 1
//#define CONFIG_DMA2_Stream5_USER_IRQ 1
//#define CONFIG_DMA2_Stream6_USER_IRQ 1
//#define CONFIG_DMA2_Stream7_USER_IRQ 1
//#define CONFIG_USART6_USER_IRQ 1
//#define CONFIG_I2C3_EV_USER_IRQ 1
//#define CONFIG_I2C3_ER_USER_IRQ 1
//#define CONFIG_OTG_HS_EP1_OUT_USER_IRQ 1
//#define CONFIG_OTG_HS_EP1_IN_USER_IRQ 1
//#define CONFIG_OTG_HS_WKUP_USER_IRQ 1
//#define CONFIG_OTG_HS_USER_IRQ 1
//#define CONFIG_DCMI_USER_IRQ 1
//#define CONFIG_CRYP_USER_IRQ 1
//#define CONFIG_HASH_RNG_USER_IRQ 1
//#define CONFIG_FPU_USER_IRQ 1



#endif
